### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [PowerShell/ConsoleGuiTools#210]
### Summary of the new feature / enhancement

It solves things like https://github.com/PowerShell/GraphicalTools/issues/9#issuecomment-1670246370.

### Proposed technical implementation details (optional)

My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245.

**Comment by MrFly72** [comment]
+1 Really makes sense!

**Comment by OranguTech** [comment]
This can be closed, since discussions are open. (Though not used really, yet)
